/*

 CINEMATIC2_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : cinematic2.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cinematic2_mapWidth 20
#define cinematic2_mapHeight 18
#define cinematic2_mapBank 0

#define cinematic2_map cinematic2_mapPLN0
extern unsigned char cinematic2_mapPLN0[];

/* End of CINEMATIC2_MAP.H */
